version: '3.7'
services:
    ui:
        restart: always
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        container_name: ui
        image: zemuldo/site-ui
        labels:
        - com.centurylinklabs.watchtower.enable=true

    watchtower:
        image: v2tec/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always