name: Publish GRC
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
   
    - name: Build and Push
      uses: zemuldo/grc-docker-build-push@master
      with:
       registry_url: "gcr.io/zemuldo-com-website-blog"
       gcloud_auth: ${{ secrets.GCLOUD_AUTH }},
       image_name: "site-ui"
       image_tag: "latest"

    