name: Publish GRC

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish to GRC
    steps:
    - name: Publish Image
      uses: actions/gcloud/auth@master

    - name: Authenticate Google Cloud
      run: |
        cat $HOME/gcloud.json
        gcloud --version

