name: Build & Publish
on: 
  push:
      branches:    
          - master
jobs:
  to_gcr_io:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Env Variables
      run: |
        touch .env.production
        echo BASE_URL=${{ secrets.PROD_BASE_URL }} >> .env.production
        echo PORT=3000 >> .env.production
        echo BASE_URL_DOMAIN=${{ secrets.PROD_BASE_URL_DOMAIN }} >> .env.production
        echo API_URL=${{ secrets.PROD_API_URL }} >> .env.production
        echo GA_TRACKING_ID=${{ secrets.PROD_GA_TRACKING_ID }} >> .env.production

    - name: Build and Push
      uses: zemuldo/docker-build-push@master
      env:
        GA_TRACKING_ID: ${{ secrets.GA_TRACKING_ID }}
        GCLOUD_PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
        REGISTRY_URL: "gcr.io"
      with:
       image_name: "site-ui"
       image_tag: "latest"

  to_docker_io:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Setup Env Variables
      run: |
        touch .env.production
        echo BASE_URL=${{ secrets.PROD_BASE_URL }} >> .env.production
        echo PORT=3000 >> .env.production
        echo BASE_URL_DOMAIN=${{ secrets.PROD_BASE_URL_DOMAIN }} >> .env.production
        echo API_URL=${{ secrets.PROD_API_URL }} >> .env.production
        echo GA_TRACKING_ID=${{ secrets.PROD_GA_TRACKING_ID }} >> .env.production
        
    - name: Build and Push
      uses: zemuldo/docker-build-push@master
      env:
        DOCKER_USERNAME: "zemuldo"
        DOCKER_NAMESPACE: "zemuldo"
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        REGISTRY_URL: "docker.io"
      with:
       image_name: "site-ui"
       image_tag: "latest"
    

    