name: Publish GRC

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/hello-world-docker-action@v1
      with:
        who-to-greet: ${{ secrets.DOCKER_REGISTRY_URL }}
    - name: Build and Push
      uses: zemuldo/grc-docker-build-push@master
      with:
       registry_url: "grc.io"
       gcloud_auth: ${{ secrets.GCLOUD_AUTH }}
    